# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        MainWindow.setMinimumSize(QtCore.QSize(750, 500))
        MainWindow.setMaximumSize(QtCore.QSize(750, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(1, 1, 1);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px solid;\n"
"border-radius: 10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Big John PRO Light")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/1/bg.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 360, 311, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 0px solid;\n"
"        border-radius: 10px;\n"
"    \n"
"    \n"
"    color: rgb(1, 1, 1);\n"
"    font: 8pt \"Big John PRO Light\";\n"
"    \n"
"    \n"
"    background-image: url(:/1/icons/btn.png);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    \n"
"\n"
"\n"
"\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 420, 51, 43))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 0px solid;\n"
"        border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    image: url(:/1/icons/github.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 460, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Big John PRO")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(252, 68, 68);")
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 360, 21, 21))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: 0px solid;\n"
"        border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-image: url(:/1/icons/cil-check-alt.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 390, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Big John PRO Light")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pointer"))
        self.label_3.setText(_translate("MainWindow", "Say everything, Fuck everyone."))
        self.label.setText(_translate("MainWindow", "ex: Gym, 365 days, 200$"))
import qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

import qrc_rc